# standard jekyll configuration
permalink: /blog/:year/:month/:title
safe: true
lsi: false
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: dale-williams.com
title: Dale Williams
description: Software developer, specialising in web development and all things .Net.
keywords: dale williams
author:
  twitter: enslam
email: dale@dale-williams.com

# configuration for ehancements, uncomment to enable

feedburner:
  id: DaleWilliams

#google_analytics:
#  account: UA-20275850-1

github:
  url: https://dale-williams.com
#   username: ghusername

disqus:
  id: dalewilliams

plugins:
  - jekyll-seo-tag

twitter:
  username: enslam
  card: summary

facebook:
  publisher: thedalewilliams

social:
  name: Dale Williams
  links:
    - https://twitter.com/enslam
    - https://www.facebook.com/thedalewilliams
    - https://www.linkedin.com/in/dale-williams
    - https://plus.google.com/u/0/104898452951590306204
    - https://github.com/thedalewilliams
    - https://www.youtube.com/channel/UCCc-jg3hxxL-0RHc6GK5yOA

#webmaster_verifications:
#  google: 1234
#  bing: 1234
#  alexa: 1234
#  yandex: 1234
#  baidu: 1234

